### ISSUE TITLE
The example doesn't work

### ISSUE THREAD

**Issue by icetee** [Clever/unix-sort#8]
I tired two example. How used your code?

var ArrayStream = require('arraystream');
var unix_sort = require('unix-sort');

var array = ['a', 'e', 'b', 'd', 'e', 'c'];
var objects = array.map(function (el) {return {item: el}});

var readable = new ArrayStream(objects);
readable.pipe(unix_sort(['item']))
	.on('data', function(record) {
		console.log(record);
	});

--------

D:\x\node_modules\understream\lib-js\understream.js:115
      return source.unpipe(_this).pipe(_this.head);
                    ^

TypeError: source.unpipe is not a function
    at StreamCombiner.<anonymous> (D:\x\node_modules\understream\lib-js\understream.js:115:21)
    at emitOne (events.js:77:13)
    at StreamCombiner.emit (events.js:169:7)
    at ArrayStream.Stream.pipe (stream.js:103:8)
    at Object.<anonymous> (D:\x\index.js:20:10)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:467:10)

**Comment by doodles526** [comment]
@icetee It looks from your stack-trace that you are trying to run this on Windows? This library only works on a UNIX system with the sort command line program.

**Comment by doodles526** [comment]
Also, while it isn't your problem if you're running on windows, it also is dependent on the UNIX cut program being installed
